### PR TITLE
Library list done

### PR DESCRIPTION
**Pull request by retkiewi**
Done from a visual standpoint, needs connection with backend. Currently inaccessible. To test add route in router with link to this component.

### CODE REVIEW

**Review by Iffern — APPROVED** [review]
From a frontend perspective everything looks fine - backend functionalities need to be added

**Review by kuczi55 — APPROVED** [review]
For now everything looks ok. I have no objections

**Review by kuczi55 — CHANGES_REQUESTED** [review]
Could you merge/rebase main branch to yours?

**Review by kuczi55 — APPROVED** [review]
After short conversation we decided that changes are not needed

**Pull request merged**
